### ISSUE TITLE
User can add redirects to their own address, limited by a number of max redirects

### ISSUE THREAD

**Issue by ohartl** [ohartl/webmum#27]
Shouldn't a list like that exist?

And should this be displayed directly in the personal dashboard or an own page?

**Comment by ThomasLeister** [comment]
Great idea, @ohartl ! We could introduce a new page for that ... with a link to it on the personal dashboard. The page could give information about existing aliases and maybe the user will be able to create aliases himself in the future? The administrator could assign e.g. 5 aliases for that user... and the user chooses, which aliases he wants to use.

**Comment by ohartl** [comment]
Nice idea. The user should only be able to create alias (1-to-1 redirect) to himself then i guess?! And also he shouldn't be able to enter himself into maillists (1-to-n redirect) right?

**Comment by ohartl** [comment]
@ThomasLeister list is implemented with 4dc50750c9662263d49d4cee1724f7379a439876
Creating aliases on their own still needs to be done.

**Comment by ohartl** [comment]
Given a maximum number of redirects for a user, should all redirect types be counted

@ThomasLeister I need some feedback to this.

**Comment by ohartl** [comment]
Feature implemented, ready for testing.
Still need to write a README text before closing this.
