### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by ohartl** [ohartl/webmum#34]
while installed flag is not set, the user cannot access use other pages then installation.

1. getting started
   - info
   - ask for write access in `config/`
   - other requirements (php, php settings, ..)

2. database
   - install basic database schema if not already exists (ask the user)
   - otherwise: give them the option to map the database
   - save database configuration

3. general configuration of WebMUM
   - encryption algorithm, set password length
   - mailbox limit or no?
   - multi source redirects or no?
   - validate that redirect source addresses are using domains installed?
   - front end options

4. admin setup
   - ask if admin/admins already exists or create them
   - add admin/admins to configuration

5. final step
   - before: set installed flag -> not installation possible anymore
   - require user to remove write access dir `config/` again

6. finished
   - maybe the give user a little introduction

**Comment by ThomasLeister** [comment]
Sounds great :+1:

**Comment by ohartl** [comment]
I am currently working on it in branch dev-installer, and will update here as soon as testing is possible.

See PR #52 for more information.
